[build]
publish = "dist"
command = "cross-env IS_SERVERLESS=true && pnpm run build:pls && pnpm run build:thumbnail && build:vercel"

[build.environment]
NODE_VERSION = "20.18.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
