[build]
publish = "dist"
command = "pnpm run build:pls && pnpm run build:thumbnail && pnpm run build"

[build.environment]
NODE_VERSION = "20.18.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
