name: Publish Site

on:
  push:
    branches:
      - 'main'
    paths:
      - '**'  # 监控所有文件的变更，包括子模块
  pull_request:
    branches:
      - 'main'
    paths:
      - '**'  # 监控所有文件的变更，包括子模块
  # schedule:
  #   - cron: "22 22 * * *"

jobs:
  site:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive' # 检出子模块
      - uses: ./.github/setup

      - run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - run: |
          echo "PUPPETEER_EXECUTABLE_PATH=$(which google-chrome)" >> $GITHUB_ENV
      - run: pnpm run build:pls
      - run: pnpm run build:thumbnail
      - run: pnpm run build
      - run: cp dist/index.html dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: dist
          cname: blog.sakitam.com
